version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.example
    image: nodos-app
    command: nodos server -h 0.0.0.0
  caddy:
    container_name: caddy
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app