version: '3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.production
    image: devops-for-programmers-project-lvl1:dev
    command: npm test
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13.2
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}