name: push

on:
  push:
    branches:
      - main

env:
  APP_IMAGE_NAME: 3102033310121/devops-for-programmers-project-lvl1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Node install
        run: npm install

      - name: Test
        run: npx jest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest